from django.urls import path

from .views import (
    FriendListView,
    FriendRequestAcceptView,
    FriendRequestCreateView,
    FriendRequestListView,
    FriendSearchView,
    GroupCreateView,
    GroupExitView,
    GroupInfoView,
    GroupListView,
    GroupMemberManageView,
    GroupMessagesView,
    GroupUnreadCountsView,
    LastMessageView,
    MessageListView,
    MessageReactionView,
    MessageUploadView,
    UnreadCountsView,
    UsersSearchView,
)

urlpatterns = [
    path('users', UsersSearchView.as_view(), name='chat-user-search'),
    path('friend_request', FriendRequestCreateView.as_view(), name='chat-friend-request'),
    path('friend_requests/<int:user_id>', FriendRequestListView.as_view(), name='chat-friend-request-list'),
    path('accept_request/<int:request_id>', FriendRequestAcceptView.as_view(), name='chat-friend-request-accept'),
    path('friends/<int:user_id>', FriendListView.as_view(), name='chat-friends'),
    path('friends/<int:user_id>/search', FriendSearchView.as_view(), name='chat-friend-search'),
    path('unread_counts/<int:user_id>', UnreadCountsView.as_view(), name='chat-unread-counts'),
    path('group_unread_counts/<int:user_id>', GroupUnreadCountsView.as_view(), name='chat-group-unread-counts'),
    path('last_message/<int:friend_id>', LastMessageView.as_view(), name='chat-last-message'),
    path('messages/<int:identifier>', MessageListView.as_view(), name='chat-messages'),
    path('messages/<int:message_id>/react', MessageReactionView.as_view(), name='chat-message-reaction'),
    path('group_messages/<int:group_id>', GroupMessagesView.as_view(), name='chat-group-messages'),
    path('group_messages/<int:message_id>/react', MessageReactionView.as_view(), name='chat-group-message-reaction'),
    path('groups', GroupCreateView.as_view(), name='chat-group-create'),
    path('groups/<int:user_id>', GroupListView.as_view(), name='chat-group-list'),
    path('groups/<int:group_id>/<str:action>', GroupMemberManageView.as_view(), name='chat-group-manage'),
    path('groups/<int:group_id>/exit', GroupExitView.as_view(), name='chat-group-exit'),
    path('group_info/<int:group_id>', GroupInfoView.as_view(), name='chat-group-info'),
    path('upload/<str:scope>/<int:target_id>', MessageUploadView.as_view(), name='chat-upload'),
]
