from django.core.management.base import BaseCommand
from django.db import connection
from django.core.management import call_command


class Command(BaseCommand):
    help = 'Create attendance table if it does not exist'

    def handle(self, *args, **options):
        with connection.cursor() as cursor:
            # Check if table exists
            try:
                cursor.execute("""
                    SELECT EXISTS (
                        SELECT FROM information_schema.tables 
                        WHERE table_schema = 'public' 
                        AND table_name = 'attendance'
                    );
                """)
                table_exists = cursor.fetchone()[0]
            except Exception as e:
                self.stdout.write(self.style.WARNING(f'Error checking table: {e}'))
                table_exists = False
            
            if table_exists:
                self.stdout.write(self.style.SUCCESS('Attendance table already exists.'))
                return
            
            # First, try to run all migrations to ensure dependencies exist
            self.stdout.write('Running migrations to ensure dependencies exist...')
            try:
                call_command('migrate', '--run-syncdb', verbosity=0)
            except Exception as e:
                self.stdout.write(self.style.WARNING(f'Note: {e}'))
            
            # Create the table (without foreign keys first if dependencies don't exist)
            self.stdout.write('Creating attendance table...')
            try:
                cursor.execute("""
                    CREATE TABLE IF NOT EXISTS "attendance" (
                        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        "date" date NOT NULL,
                        "status" varchar(20) NOT NULL CHECK (status IN ('present', 'absent', 'late', 'excused')),
                        "remarks" text NULL,
                        "check_in_time" time NULL,
                        "check_out_time" time NULL,
                        "hours_attended" decimal(4,2) NULL,
                        "created_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        "updated_at" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        "course_id" integer NOT NULL,
                        "student_id" integer NOT NULL,
                        "teacher_id" integer NOT NULL
                    );
                """)
                
                # Try to add unique constraint
                try:
                    cursor.execute("""
                        ALTER TABLE "attendance" 
                        ADD CONSTRAINT "attendance_student_id_course_id_date_4b006b8e_uniq" 
                        UNIQUE ("student_id", "course_id", "date");
                    """)
                except Exception as e:
                    self.stdout.write(self.style.WARNING(f'Could not add unique constraint: {e}'))
                
                # Try to add foreign key constraints (only if referenced tables exist)
                try:
                    cursor.execute("""
                        SELECT EXISTS (
                            SELECT FROM information_schema.tables 
                            WHERE table_schema = 'public' 
                            AND table_name = 'course'
                        );
                    """)
                    course_exists = cursor.fetchone()[0]
                    
                    if course_exists:
                        cursor.execute("""
                            ALTER TABLE "attendance" 
                            ADD CONSTRAINT "attendance_course_id_f752d7fa_fk_course_course_id" 
                            FOREIGN KEY ("course_id") REFERENCES "course" ("course_id") 
                            DEFERRABLE INITIALLY DEFERRED;
                        """)
                except Exception as e:
                    self.stdout.write(self.style.WARNING(f'Could not add course foreign key: {e}'))
                
                try:
                    cursor.execute("""
                        SELECT EXISTS (
                            SELECT FROM information_schema.tables 
                            WHERE table_schema = 'public' 
                            AND table_name = 'student_registration'
                        );
                    """)
                    student_exists = cursor.fetchone()[0]
                    
                    if student_exists:
                        cursor.execute("""
                            ALTER TABLE "attendance" 
                            ADD CONSTRAINT "attendance_student_id_d55196c7_fk_student_registration_student_id" 
                            FOREIGN KEY ("student_id") REFERENCES "student_registration" ("student_id") 
                            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
                        """)
                except Exception as e:
                    self.stdout.write(self.style.WARNING(f'Could not add student foreign key: {e}'))
                
                # Add teacher foreign key
                try:
                    cursor.execute("""
                        SELECT EXISTS (
                            SELECT FROM information_schema.tables 
                            WHERE table_schema = 'public' 
                            AND table_name = 'teacher_registration'
                        );
                    """)
                    teacher_exists = cursor.fetchone()[0]
                    
                    if teacher_exists:
                        cursor.execute("""
                            ALTER TABLE "attendance" 
                            ADD CONSTRAINT "attendance_teacher_id_fk_teacher_registration_teacher_id" 
                            FOREIGN KEY ("teacher_id") REFERENCES "teacher_registration" ("teacher_id") 
                            ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
                        """)
                except Exception as e:
                    self.stdout.write(self.style.WARNING(f'Could not add teacher foreign key: {e}'))
                
                # Create indexes
                try:
                    cursor.execute("""
                        CREATE INDEX IF NOT EXISTS "attendance_course_id_f752d7fa" 
                        ON "attendance" ("course_id");
                    """)
                    
                    cursor.execute("""
                        CREATE INDEX IF NOT EXISTS "attendance_student_id_d55196c7" 
                        ON "attendance" ("student_id");
                    """)
                    
                    cursor.execute("""
                        CREATE INDEX IF NOT EXISTS "attendance_teacher_id" 
                        ON "attendance" ("teacher_id");
                    """)
                    
                    cursor.execute("""
                        CREATE INDEX IF NOT EXISTS "attendance_date" 
                        ON "attendance" ("date");
                    """)
                    
                    cursor.execute("""
                        CREATE INDEX IF NOT EXISTS "attendance_student_date" 
                        ON "attendance" ("student_id", "date");
                    """)
                    
                    cursor.execute("""
                        CREATE INDEX IF NOT EXISTS "attendance_status" 
                        ON "attendance" ("status");
                    """)
                except Exception as e:
                    self.stdout.write(self.style.WARNING(f'Could not create indexes: {e}'))
                
                self.stdout.write(self.style.SUCCESS('Successfully created attendance table!'))
                
            except Exception as e:
                self.stdout.write(self.style.ERROR(f'Error creating table: {e}'))
                raise

